import type { ModuleDefinition, UserRole } from '@/types'

export const MODULES: ModuleDefinition[] = [
  {
    id: 1,
    slug: 'modulo-1',
    name: 'Bot de Contenido',
    description: 'Panel de control del bot de Instagram. Gestiona modelos, ejecuta el bot y revisa logs de ejecuciones.',
    icon: 'Bot',
    phase: 2,
    allowedRoles: ['admin', 'manager', 'creativo'],
    isBuilt: true,
  },
  {
    id: 2,
    slug: 'modulo-2',
    name: 'Analytics & Referencias',
    description: 'Métricas de cuentas propias e inteligencia de competencia por nicho. Ratio views/likes, top reels y banco de referencias.',
    icon: 'BarChart3',
    phase: 3,
    allowedRoles: ['admin', 'manager', 'creativo'],
    isBuilt: true,
  },
  {
    id: 3,
    slug: 'modulo-3',
    name: 'Finanzas y Facturación',
    description: 'Genera facturas PDF, registra gastos por modelo y visualiza márgenes netos en tiempo real.',
    icon: 'DollarSign',
    phase: 4,
    allowedRoles: ['admin'],
    isBuilt: false,
  },
  {
    id: 4,
    slug: 'modulo-4',
    name: 'Control de Chatters',
    description: 'Registro de calidad, reportes de ventas por turno y métricas de rendimiento con Infloww.',
    icon: 'MessageSquare',
    phase: 8,
    allowedRoles: ['admin', 'manager', 'team_leader', 'chatter'],
    isBuilt: false,
  },
  {
    id: 5,
    slug: 'modulo-5',
    name: 'Analytics de Cuentas',
    description: 'Registro semanal de seguidores y audiencia. Gráficas de crecimiento e historial de estados.',
    icon: 'BarChart3',
    phase: 5,
    allowedRoles: ['admin', 'manager', 'team_leader', 'va', 'modelo'],
    isBuilt: false,
  },
  {
    id: 6,
    slug: 'modulo-6',
    name: 'Pipeline de Reclutamiento',
    description: 'Kanban de candidatas: desde la aplicación hasta la firma. Sincronizado con Airtable.',
    icon: 'Users',
    phase: 9,
    allowedRoles: ['admin', 'manager'],
    isBuilt: false,
  },
  {
    id: 7,
    slug: 'modulo-7',
    name: 'Calendario de Contenido',
    description: 'Control de entregas semanales y puntualidad. Historial por modelo con semáforo de cumplimiento.',
    icon: 'Calendar',
    phase: 6,
    allowedRoles: ['admin', 'manager', 'team_leader', 'modelo'],
    isBuilt: false,
  },
  {
    id: 8,
    slug: 'modulo-8',
    name: 'Sistema de Alertas',
    description: 'Detección automática de situaciones críticas: cuentas sin crecimiento, facturas pendientes y más.',
    icon: 'Bell',
    phase: 7,
    allowedRoles: ['admin', 'manager', 'team_leader'],
    isBuilt: false,
  },
  {
    id: 9,
    slug: 'modulo-9',
    name: 'Biblioteca de Assets',
    description: 'Repositorio de contexto por modelo: referencias, paleta, tono de voz y estrategia.',
    icon: 'FolderOpen',
    phase: 10,
    allowedRoles: ['admin', 'manager'],
    isBuilt: false,
  },
  {
    id: 10,
    slug: 'modulo-10',
    name: 'Onboarding de Modelos',
    description: 'Flujo automático al dar de alta una nueva modelo: Drive, Notion, checklist y notificaciones.',
    icon: 'UserPlus',
    phase: 11,
    allowedRoles: ['admin', 'manager'],
    isBuilt: false,
  },
  {
    id: 11,
    slug: 'modulo-11',
    name: 'Centro de Comunicación',
    description: 'Tablón de briefings e instrucciones con confirmación de lectura. Lo que se pierde en WhatsApp, aquí queda.',
    icon: 'Megaphone',
    phase: 12,
    allowedRoles: ['admin', 'manager', 'team_leader', 'chatter', 'va', 'modelo'],
    isBuilt: false,
  },
]

export function getAccessibleModules(role: UserRole): ModuleDefinition[] {
  if (role === 'admin') return MODULES
  return MODULES.filter((m) => m.allowedRoles.includes(role))
}
// deploy Sun Aug 16 20:49:27 +04 2026
